/**
 * Serendipity Engine — Decomposition Engine
 *
 * Reverse-scaffolding: takes an existing story/manuscript and breaks it down
 * into the engine's 8-phase structure. This is used for:
 * - Analyzing existing works (Wizard of Oz example)
 * - Importing user manuscripts for editing
 * - Learning from published works
 *
 * The decomposition runs as a series of LLM calls, each extracting a different
 * dimension from the source text.
 */

import { removeEmdashes } from '../lib/randomEngine.js';

/**
 * Define the decomposition pipeline steps
 */
export const DECOMPOSITION_STEPS = [
  { key: 'author', label: 'Author Voice', phase: 1, description: 'Extract writing style and voice' },
  { key: 'narrator', label: 'Narrator Analysis', phase: 2, description: 'Identify narrator and perspective' },
  { key: 'world', label: 'World Building', phase: 3, description: 'Extract world details and setting' },
  { key: 'characters', label: 'Character Profiles', phase: 4, description: 'Profile major characters' },
  { key: 'relationships', label: 'Relationships', phase: 5, description: 'Map character relationships' },
  { key: 'structure', label: 'Story Structure', phase: 6, description: 'Extract plot arc and structure' },
  { key: 'review', label: 'Structural Review', phase: 7, description: 'Analyze and review structure' },
  { key: 'chapters', label: 'Chapter Split', phase: 8, description: 'Organize into chapters' },
];

/**
 * Decompose an entire story/manuscript into Serendipity Engine project structure
 *
 * @param {Function} sendMessage - LLM communication function (returns { success, content, error })
 * @param {string} sourceText - The full manuscript text to decompose
 * @param {object} options - Configuration
 *   - title: Story title (extracted from sourceText if not provided)
 *   - onProgress: Callback function called after each step with { step, completed, total }
 * @returns {{ files: { path: content }, metadata: { title, wordCount, steps } }}
 */
export async function decomposeStory(sendMessage, sourceText, options = {}) {
  if (!sourceText?.trim()) {
    throw new Error('Source text is required for decomposition');
  }

  const { onProgress, title: providedTitle } = options;
  const cleanText = sourceText.trim();
  const metadata = {
    wordCount: cleanText.split(/\s+/).length,
    title: providedTitle || extractTitleHeuristic(cleanText),
    sourceLength: cleanText.length,
    steps: [],
  };

  const files = {};
  const totalSteps = DECOMPOSITION_STEPS.length;

  // Run each decomposition step in sequence
  for (let i = 0; i < DECOMPOSITION_STEPS.length; i++) {
    const step = DECOMPOSITION_STEPS[i];

    try {
      if (onProgress) {
        onProgress({ step: step.key, label: step.label, completed: i, total: totalSteps });
      }

      const result = await decomposeStep(sendMessage, cleanText, step, files, metadata);

      // Merge files and metadata from this step
      Object.assign(files, result.files);
      metadata.steps.push({
        key: step.key,
        label: step.label,
        success: true,
        fileCount: Object.keys(result.files).length,
      });
    } catch (err) {
      console.warn(`Decomposition step ${step.key} failed:`, err);
      metadata.steps.push({
        key: step.key,
        label: step.label,
        success: false,
        error: err.message,
      });

      // Continue to next step even if one fails
      // But create a minimal placeholder
      const placeholder = createPlaceholder(step.key);
      Object.assign(files, placeholder);
    }
  }

  if (onProgress) {
    onProgress({ step: 'complete', label: 'Complete', completed: totalSteps, total: totalSteps });
  }

  return { files, metadata };
}

/**
 * Run a single decomposition step
 *
 * @param {Function} sendMessage - LLM communication function
 * @param {string} sourceText - Full manuscript text
 * @param {object} step - Step definition { key, label, phase }
 * @param {object} previousFiles - Files generated by previous steps
 * @param {object} metadata - Metadata from previous steps
 * @returns {{ files: { path: content } }}
 */
export async function decomposeStep(sendMessage, sourceText, step, previousFiles = {}, metadata = {}) {
  const { key, label } = step;
  let prompt;
  const files = {};

  switch (key) {
    case 'author':
      prompt = buildAuthorVoicePrompt(sourceText);
      const authorResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2000,
      });

      if (authorResult.success) {
        const cleaned = removeEmdashes(authorResult.content);
        files['author.md'] = formatAuthorMarkdown(cleaned);
      } else {
        throw new Error(authorResult.error || 'Author voice extraction failed');
      }
      break;

    case 'narrator':
      prompt = buildNarratorPrompt(sourceText);
      const narratorResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 1500,
      });

      if (narratorResult.success) {
        const cleaned = removeEmdashes(narratorResult.content);
        files['narrator.md'] = formatNarratorMarkdown(cleaned);
      } else {
        throw new Error(narratorResult.error || 'Narrator analysis failed');
      }
      break;

    case 'world':
      prompt = buildWorldBuildingPrompt(sourceText);
      const worldResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2500,
      });

      if (worldResult.success) {
        const cleaned = removeEmdashes(worldResult.content);
        files['world/world-building.md'] = formatWorldMarkdown(cleaned);
      } else {
        throw new Error(worldResult.error || 'World building extraction failed');
      }
      break;

    case 'characters':
      prompt = buildCharacterProfilesPrompt(sourceText);
      const charsResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 3000,
      });

      if (charsResult.success) {
        const cleaned = removeEmdashes(charsResult.content);
        const characterFiles = parseCharacterMarkdown(cleaned);
        Object.assign(files, characterFiles);
      } else {
        throw new Error(charsResult.error || 'Character profile extraction failed');
      }
      break;

    case 'relationships':
      prompt = buildRelationshipsPrompt(sourceText, previousFiles);
      const relResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2000,
      });

      if (relResult.success) {
        const cleaned = removeEmdashes(relResult.content);
        files['relationships/questions-answered.md'] = formatRelationshipsMarkdown(cleaned);
      } else {
        throw new Error(relResult.error || 'Relationships extraction failed');
      }
      break;

    case 'structure':
      prompt = buildStructurePrompt(sourceText);
      const structResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2500,
      });

      if (structResult.success) {
        const cleaned = removeEmdashes(structResult.content);
        const structFiles = parseStructureMarkdown(cleaned);
        Object.assign(files, structFiles);
      } else {
        throw new Error(structResult.error || 'Structure extraction failed');
      }
      break;

    case 'review':
      prompt = buildReviewPrompt(sourceText, previousFiles, metadata);
      const reviewResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 1500,
      });

      if (reviewResult.success) {
        const cleaned = removeEmdashes(reviewResult.content);
        files['dry-run-audit.md'] = formatReviewMarkdown(cleaned);
      } else {
        throw new Error(reviewResult.error || 'Structural review failed');
      }
      break;

    case 'chapters':
      prompt = buildChapterSplitPrompt(sourceText, previousFiles['outline.md']);
      const chaptersResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 4000,
      });

      if (chaptersResult.success) {
        const cleaned = removeEmdashes(chaptersResult.content);
        const chapterFiles = parseChapterMarkdown(cleaned);
        Object.assign(files, chapterFiles);
      } else {
        throw new Error(chaptersResult.error || 'Chapter split failed');
      }
      break;

    default:
      throw new Error(`Unknown decomposition step: ${key}`);
  }

  return { files };
}

// ─── Prompt Builders ────────────────────────────────────────────────────

function buildAuthorVoicePrompt(sourceText) {
  return `You are analyzing a manuscript to extract the author's voice profile for the Serendipity Engine.

MANUSCRIPT EXCERPT (first 3000 chars):
${sourceText.substring(0, 3000)}

${sourceText.length > 3000 ? `[...manuscript continues for ${sourceText.length} total characters...]` : ''}

Extract and format the following as markdown:

# Author Voice Profile

## Writing Style
- Sentence structure (simple/complex, average length)
- Vocabulary sophistication (academic/casual/vernacular)
- Rhythm and pacing
- Use of metaphor, simile, and imagery

## Distinctive Patterns
- Recurring phrases, idioms, or speech patterns
- Punctuation preferences
- Dialogue style (if present)
- Narrative perspective and distance

## Emotional Tone
- Overall mood and atmosphere
- Emotional register (somber/humorous/romantic/etc.)
- Intensity level

## Influences and References
- Apparent literary influences
- Genre conventions followed or subverted
- Notable stylistic choices

Provide specific textual examples for each observation.`;
}

function buildNarratorPrompt(sourceText) {
  return `Analyze the narrative perspective and narrator characteristics in this manuscript.

TEXT (first 2000 chars):
${sourceText.substring(0, 2000)}

Format as markdown:

# Narrator Analysis

## Narrative Perspective
- Point of view (first-person, third-person, second-person, omniscient)
- Narrative distance (intimate/distant)
- Reliability (reliable/unreliable narrator)

## Narrator Identity
- Who is the narrator (character, external observer, etc.)
- Age and background if determinable
- Knowledge limitations or special insights

## Narrator's Voice
- Distinctive speech patterns or characteristics
- Level of intrusion into the story
- Relationship to the reader

## Narrative Techniques
- Use of foreshadowing, flashbacks
- Direct address to reader
- Asides or commentary`;
}

function buildWorldBuildingPrompt(sourceText) {
  return `Extract all world-building details from this manuscript.

TEXT:
${sourceText.substring(0, 4000)}

Format as markdown with these sections:

# World Building

## Setting and Geography
- Physical location(s)
- Climate and season
- Landscape and terrain
- Notable landmarks

## Time and Era
- Historical period or year
- Technology level
- Social development stage

## Culture and Society
- Social structures and hierarchies
- Customs and traditions
- Values and beliefs
- Laws and systems

## Magic/Science Systems (if applicable)
- Rules and mechanics
- Limitations and costs
- Common applications

## Economics
- Currency and trade
- Resource scarcity
- Class divisions or wealth distribution

## Conflicts and Tensions
- External threats or challenges
- Internal social conflicts
- World-specific problems

Include specific textual references.`;
}

function buildCharacterProfilesPrompt(sourceText) {
  return `Extract and profile all major characters from this manuscript.

TEXT (first 3500 chars):
${sourceText.substring(0, 3500)}

For each major character, create a markdown section:

# Characters

## [Character Name]
- **Role**: Protagonist, antagonist, supporting, etc.
- **Physical Description**: Age, appearance, distinctive features
- **Personality**: Key traits, temperament
- **Motivations**: What drives them
- **Relationships**: Key connections to other characters
- **Arc**: Growth or change over the story
- **Conflicts**: Internal and external struggles
- **Memorable Moments**: Key scenes or quotes revealing character

Prioritize characters by importance. Include 3-8 major characters depending on manuscript scope.`;
}

function buildRelationshipsPrompt(sourceText, previousFiles) {
  const charContext = previousFiles['characters/'] ?
    '(Character files available)' :
    '(Extract from text)';

  return `Map character relationships and dynamics from this manuscript.

TEXT:
${sourceText.substring(0, 2500)}

${charContext}

Create a markdown response:

# Relationship Mapping

## Key Relationships
For each significant relationship:
- **Characters Involved**: Names and roles
- **Relationship Type**: Family, romantic, mentor, rivalry, friendship, etc.
- **History**: How they met, relationship evolution
- **Tension/Harmony**: Conflicts or bonds
- **Impact on Story**: How relationship drives plot

## Dynamics
- Power dynamics and hierarchies
- Alliances and enemies
- Love triangles or complex entanglements
- Unresolved conflicts

## Questions About Relationships
- What do characters want from each other?
- What misunderstandings exist?
- How do relationships create obstacles or opportunities?`;
}

function buildStructurePrompt(sourceText) {
  return `Analyze the narrative structure and story arc of this manuscript.

TEXT:
${sourceText.substring(0, 5000)}

Format as markdown:

# Story Structure

## Overall Arc
- **Inciting Incident**: What kicks off the plot
- **Rising Action**: Building tension and complications
- **Climax**: The peak moment
- **Falling Action**: Resolution of tension
- **Resolution**: How things conclude

## Three-Act Structure
- **Act 1**: Setup (approximate location in manuscript)
- **Act 2**: Confrontation (approximate location)
- **Act 3**: Resolution (approximate location)

## Plot Outline
Create a chapter-by-chapter outline showing:
- Major plot points
- Character developments
- World revelations
- Turning points

## Pacing
- Fast sections and slow sections
- Scene balance
- Information revelation strategy

## Themes
- Central theme(s)
- How they're developed
- Resolution of thematic questions`;
}

function buildReviewPrompt(sourceText, previousFiles, metadata) {
  return `Conduct a structural review of this decomposed manuscript.

SOURCE MANUSCRIPT (first 2000 chars):
${sourceText.substring(0, 2000)}

ANALYSIS COMPLETED:
- Author voice: ${previousFiles['author.md'] ? 'yes' : 'no'}
- Narrator: ${previousFiles['narrator.md'] ? 'yes' : 'no'}
- World building: ${previousFiles['world/world-building.md'] ? 'yes' : 'no'}
- Character profiles: ${Object.keys(previousFiles).filter(p => p.startsWith('characters/')).length || 0} files
- Story structure: ${previousFiles['outline.md'] || previousFiles['story/arc.md'] ? 'yes' : 'no'}

REVIEW ASSESSMENT:

# Structural Review

## Completeness
- What story elements are well-established?
- What gaps or unclear areas remain?
- Are all major characters profiled?

## Consistency
- Do character profiles match their actions in the text?
- Is the world internally consistent?
- Do relationships match the interaction patterns?

## Clarity
- Is the story structure clear?
- Are the central conflicts evident?
- Can the narrative arc be followed?

## Readiness for Engine
- Is the decomposition sufficient for engine reconstruction?
- What additional work would strengthen the project?
- Confidence level (low/medium/high)?

## Recommendations
- Priority improvements
- Clarifications needed
- Next steps for the author`;
}

function buildChapterSplitPrompt(sourceText, outlineContent) {
  return `Split this manuscript into chapter-sized sections aligned with the story structure.

FULL TEXT:
${sourceText}

${outlineContent ? `OUTLINE PROVIDED:
${outlineContent}` : 'NO OUTLINE PROVIDED - infer chapter boundaries from narrative structure'}

Create chapter markdown files with this format for each chapter:

# Chapter [N]: [Title]

[Chapter content]

Guidelines:
- Aim for 2000-4000 words per chapter
- Break at natural scene transitions
- Each chapter should have narrative momentum
- Title chapters meaningfully
- Number sequentially starting from 1

Output the entire manuscript re-divided into chapters, preserving all original text.`;
}

// ─── Markdown Formatters ────────────────────────────────────────────────

function formatAuthorMarkdown(content) {
  // Ensure proper markdown formatting
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Author Voice\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatNarratorMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Narrator\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatWorldMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# World Building\n\n${formatted}`;
  }
  return formatted.trim();
}

function parseCharacterMarkdown(content) {
  const files = {};
  // Split by character sections
  const sections = content.split(/^## /m).slice(1);

  sections.forEach((section) => {
    const lines = section.split('\n');
    const charName = lines[0].trim();
    const safeName = charName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    files[`characters/${safeName}.md`] = `## ${section}`.trim();
  });

  return files;
}

function parseStructureMarkdown(content) {
  const files = {};

  // Separate outline and arc from the response
  const outlineMatch = content.match(/^#+.*Outline[\s\S]*?(?=^#+|$)/m);
  const arcMatch = content.match(/^#+.*Arc[\s\S]*?(?=^#+|$)/m);

  if (outlineMatch) {
    files['outline.md'] = outlineMatch[0].trim();
  } else {
    files['outline.md'] = extractOutlineSection(content);
  }

  if (arcMatch) {
    files['story/arc.md'] = arcMatch[0].trim();
  } else {
    files['story/arc.md'] = extractArcSection(content);
  }

  return files;
}

function formatRelationshipsMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Relationships\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatReviewMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Structural Review\n\n${formatted}`;
  }
  return formatted.trim();
}

function parseChapterMarkdown(content) {
  const files = {};
  const chapters = content.split(/^# Chapter /m).slice(1);

  chapters.forEach((chapter, index) => {
    const chapterNum = index + 1;
    files[`story/chapter-${chapterNum}.md`] = `# Chapter ${chapter}`.trim();
  });

  return files;
}

// ─── Helper Functions ────────────────────────────────────────────────

function createPlaceholder(stepKey) {
  const placeholders = {
    author: { 'author.md': '# Author Voice\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in author voice details.' },
    narrator: { 'narrator.md': '# Narrator\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in narrator details.' },
    world: { 'world/world-building.md': '# World Building\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in world building details.' },
    characters: { 'characters/placeholder.md': '# Characters\n\n(Placeholder - decomposition step failed)\n\nPlease manually add character files.' },
    relationships: { 'relationships/questions-answered.md': '# Relationships\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in relationship details.' },
    structure: { 'outline.md': '# Outline\n\n(Placeholder)', 'story/arc.md': '# Story Arc\n\n(Placeholder)' },
    review: { 'dry-run-audit.md': '# Structural Review\n\n(Placeholder - decomposition step failed)' },
    chapters: { 'story/chapter-1.md': '# Chapter 1\n\n(Placeholder - decomposition step failed)' },
  };

  return placeholders[stepKey] || {};
}

function extractTitleHeuristic(text) {
  // Try to find a title in first few lines
  const lines = text.split('\n').slice(0, 10);
  for (const line of lines) {
    if (line.length > 5 && line.length < 100 && !line.includes('.')) {
      return line.trim();
    }
  }
  return 'Untitled Manuscript';
}

function extractOutlineSection(content) {
  // Extract the outline-like content from the response
  const lines = content.split('\n');
  const outline = [];
  let inOutline = false;

  for (const line of lines) {
    if (line.match(/outline|chapter|act/i)) {
      inOutline = true;
    }
    if (inOutline && (line.startsWith('-') || line.startsWith('*') || line.match(/^\d+\./))) {
      outline.push(line);
    }
  }

  return outline.length > 0 ? outline.join('\n') : '# Outline\n\n' + content.substring(0, 500);
}

function extractArcSection(content) {
  // Extract narrative arc from the response
  const lines = content.split('\n');
  const arc = [];
  const arcKeywords = ['inciting', 'rising', 'climax', 'falling', 'resolution'];

  for (const line of lines) {
    if (arcKeywords.some(kw => line.toLowerCase().includes(kw))) {
      arc.push(line);
    }
  }

  return arc.length > 0 ? arc.join('\n') : '# Story Arc\n\n' + content.substring(0, 500);
}
