/**
 * Serendipity Engine — Decomposition Engine
 *
 * Reverse-scaffolding: takes an existing story/manuscript and breaks it down
 * into the engine's 8-phase structure. This is used for:
 * - Analyzing existing works (Wizard of Oz example)
 * - Importing user manuscripts for editing
 * - Learning from published works
 *
 * The decomposition runs as a series of LLM calls, each extracting a different
 * dimension from the source text.
 */

import { removeEmdashes } from '../lib/randomEngine.js';
import { PROMPTS } from '../lib/promptRegistry.js';

/**
 * Define the decomposition pipeline steps
 */
export const DECOMPOSITION_STEPS = [
  { key: 'author', label: 'Author Voice', phase: 1, description: 'Extract writing style and voice' },
  { key: 'narrator', label: 'Narrator Analysis', phase: 2, description: 'Identify narrator and perspective' },
  { key: 'world', label: 'World Building', phase: 3, description: 'Extract world details and setting' },
  { key: 'characters', label: 'Character Profiles', phase: 4, description: 'Profile major characters' },
  { key: 'relationships', label: 'Relationships', phase: 5, description: 'Map character relationships' },
  { key: 'structure', label: 'Story Structure', phase: 6, description: 'Extract plot arc and structure' },
  { key: 'review', label: 'Structural Review', phase: 7, description: 'Analyze and review structure' },
  { key: 'chapters', label: 'Chapter Split', phase: 8, description: 'Organize into chapters' },
];

/**
 * Decompose an entire story/manuscript into Serendipity Engine project structure
 *
 * @param {Function} sendMessage - LLM communication function (returns { success, content, error })
 * @param {string} sourceText - The full manuscript text to decompose
 * @param {object} options - Configuration
 *   - title: Story title (extracted from sourceText if not provided)
 *   - onProgress: Callback function called after each step with { step, completed, total }
 * @returns {{ files: { path: content }, metadata: { title, wordCount, steps } }}
 */
export async function decomposeStory(sendMessage, sourceText, options = {}) {
  if (!sourceText?.trim()) {
    throw new Error('Source text is required for decomposition');
  }

  const { onProgress, title: providedTitle } = options;
  const cleanText = sourceText.trim();
  const metadata = {
    wordCount: cleanText.split(/\s+/).length,
    title: providedTitle || extractTitleHeuristic(cleanText),
    sourceLength: cleanText.length,
    steps: [],
  };

  const files = {};
  const totalSteps = DECOMPOSITION_STEPS.length;

  // Run each decomposition step in sequence
  for (let i = 0; i < DECOMPOSITION_STEPS.length; i++) {
    const step = DECOMPOSITION_STEPS[i];

    try {
      if (onProgress) {
        onProgress({ step: step.key, label: step.label, completed: i, total: totalSteps });
      }

      const result = await decomposeStep(sendMessage, cleanText, step, files, metadata);

      // Merge files and metadata from this step
      Object.assign(files, result.files);
      metadata.steps.push({
        key: step.key,
        label: step.label,
        success: true,
        fileCount: Object.keys(result.files).length,
      });
    } catch (err) {
      console.warn(`Decomposition step ${step.key} failed:`, err);
      metadata.steps.push({
        key: step.key,
        label: step.label,
        success: false,
        error: err.message,
      });

      // Continue to next step even if one fails
      // But create a minimal placeholder
      const placeholder = createPlaceholder(step.key);
      Object.assign(files, placeholder);
    }
  }

  if (onProgress) {
    onProgress({ step: 'complete', label: 'Complete', completed: totalSteps, total: totalSteps });
  }

  return { files, metadata };
}

/**
 * Run a single decomposition step
 *
 * @param {Function} sendMessage - LLM communication function
 * @param {string} sourceText - Full manuscript text
 * @param {object} step - Step definition { key, label, phase }
 * @param {object} previousFiles - Files generated by previous steps
 * @param {object} metadata - Metadata from previous steps
 * @returns {{ files: { path: content } }}
 */
export async function decomposeStep(sendMessage, sourceText, step, previousFiles = {}, metadata = {}) {
  const { key, label } = step;
  let prompt;
  const files = {};

  switch (key) {
    case 'author':
      prompt = buildAuthorVoicePrompt(sourceText);
      const authorResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2000,
      });

      if (authorResult.success) {
        const cleaned = removeEmdashes(authorResult.content);
        files['author.md'] = formatAuthorMarkdown(cleaned);
      } else {
        throw new Error(authorResult.error || 'Author voice extraction failed');
      }
      break;

    case 'narrator':
      prompt = buildNarratorPrompt(sourceText);
      const narratorResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 1500,
      });

      if (narratorResult.success) {
        const cleaned = removeEmdashes(narratorResult.content);
        files['narrator.md'] = formatNarratorMarkdown(cleaned);
      } else {
        throw new Error(narratorResult.error || 'Narrator analysis failed');
      }
      break;

    case 'world':
      prompt = buildWorldBuildingPrompt(sourceText);
      const worldResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2500,
      });

      if (worldResult.success) {
        const cleaned = removeEmdashes(worldResult.content);
        files['world/world-building.md'] = formatWorldMarkdown(cleaned);
      } else {
        throw new Error(worldResult.error || 'World building extraction failed');
      }
      break;

    case 'characters':
      prompt = buildCharacterProfilesPrompt(sourceText);
      const charsResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 3000,
      });

      if (charsResult.success) {
        const cleaned = removeEmdashes(charsResult.content);
        const characterFiles = parseCharacterMarkdown(cleaned);
        Object.assign(files, characterFiles);
      } else {
        throw new Error(charsResult.error || 'Character profile extraction failed');
      }
      break;

    case 'relationships':
      prompt = buildRelationshipsPrompt(sourceText, previousFiles);
      const relResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2000,
      });

      if (relResult.success) {
        const cleaned = removeEmdashes(relResult.content);
        files['relationships/questions-answered.md'] = formatRelationshipsMarkdown(cleaned);
      } else {
        throw new Error(relResult.error || 'Relationships extraction failed');
      }
      break;

    case 'structure':
      prompt = buildStructurePrompt(sourceText);
      const structResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 2500,
      });

      if (structResult.success) {
        const cleaned = removeEmdashes(structResult.content);
        const structFiles = parseStructureMarkdown(cleaned);
        Object.assign(files, structFiles);
      } else {
        throw new Error(structResult.error || 'Structure extraction failed');
      }
      break;

    case 'review':
      prompt = buildReviewPrompt(sourceText, previousFiles, metadata);
      const reviewResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 1500,
      });

      if (reviewResult.success) {
        const cleaned = removeEmdashes(reviewResult.content);
        files['dry-run-audit.md'] = formatReviewMarkdown(cleaned);
      } else {
        throw new Error(reviewResult.error || 'Structural review failed');
      }
      break;

    case 'chapters':
      prompt = buildChapterSplitPrompt(sourceText, previousFiles['outline.md']);
      const chaptersResult = await sendMessage({
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
        role: 'analyst',
        maxTokens: 4000,
      });

      if (chaptersResult.success) {
        const cleaned = removeEmdashes(chaptersResult.content);
        const chapterFiles = parseChapterMarkdown(cleaned);
        Object.assign(files, chapterFiles);
      } else {
        throw new Error(chaptersResult.error || 'Chapter split failed');
      }
      break;

    default:
      throw new Error(`Unknown decomposition step: ${key}`);
  }

  return { files };
}

// ─── Prompt Builders (delegated to promptRegistry.js) ───────────────────

function buildAuthorVoicePrompt(sourceText) {
  return PROMPTS.DECOMPOSE_AUTHOR.build({
    sourceExcerpt: sourceText.substring(0, 3000),
    sourceLength: sourceText.length,
  });
}

function buildNarratorPrompt(sourceText) {
  return PROMPTS.DECOMPOSE_NARRATOR.build({
    sourceExcerpt: sourceText.substring(0, 2000),
  });
}

function buildWorldBuildingPrompt(sourceText) {
  return PROMPTS.DECOMPOSE_WORLD.build({
    sourceExcerpt: sourceText.substring(0, 4000),
  });
}

function buildCharacterProfilesPrompt(sourceText) {
  return PROMPTS.DECOMPOSE_CHARACTERS.build({
    sourceExcerpt: sourceText.substring(0, 3500),
  });
}

function buildRelationshipsPrompt(sourceText, _previousFiles) {
  return PROMPTS.DECOMPOSE_RELATIONSHIPS.build({
    sourceExcerpt: sourceText.substring(0, 2500),
  });
}

function buildStructurePrompt(sourceText) {
  return PROMPTS.DECOMPOSE_STRUCTURE.build({
    sourceExcerpt: sourceText.substring(0, 5000),
  });
}

function buildReviewPrompt(sourceText, previousFiles, _metadata) {
  const analysisStatus = `- Author voice: ${previousFiles['author.md'] ? 'yes' : 'no'}
- Narrator: ${previousFiles['narrator.md'] ? 'yes' : 'no'}
- World building: ${previousFiles['world/world-building.md'] ? 'yes' : 'no'}
- Character profiles: ${Object.keys(previousFiles).filter(p => p.startsWith('characters/')).length || 0} files
- Story structure: ${previousFiles['outline.md'] || previousFiles['story/arc.md'] ? 'yes' : 'no'}`;

  return PROMPTS.DECOMPOSE_REVIEW.build({
    sourceExcerpt: sourceText.substring(0, 2000),
    analysisStatus,
  });
}

function buildChapterSplitPrompt(sourceText, outlineContent) {
  return PROMPTS.DECOMPOSE_CHAPTERS.build({
    fullText: sourceText,
    outlineContent: outlineContent || null,
  });
}

// ─── Markdown Formatters ────────────────────────────────────────────────

function formatAuthorMarkdown(content) {
  // Ensure proper markdown formatting
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Author Voice\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatNarratorMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Narrator\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatWorldMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# World Building\n\n${formatted}`;
  }
  return formatted.trim();
}

function parseCharacterMarkdown(content) {
  const files = {};
  // Split by character sections
  const sections = content.split(/^## /m).slice(1);

  sections.forEach((section) => {
    const lines = section.split('\n');
    const charName = lines[0].trim();
    const safeName = charName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    files[`characters/${safeName}.md`] = `## ${section}`.trim();
  });

  return files;
}

function parseStructureMarkdown(content) {
  const files = {};

  // Separate outline and arc from the response
  const outlineMatch = content.match(/^#+.*Outline[\s\S]*?(?=^#+|$)/m);
  const arcMatch = content.match(/^#+.*Arc[\s\S]*?(?=^#+|$)/m);

  if (outlineMatch) {
    files['outline.md'] = outlineMatch[0].trim();
  } else {
    files['outline.md'] = extractOutlineSection(content);
  }

  if (arcMatch) {
    files['story/arc.md'] = arcMatch[0].trim();
  } else {
    files['story/arc.md'] = extractArcSection(content);
  }

  return files;
}

function formatRelationshipsMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Relationships\n\n${formatted}`;
  }
  return formatted.trim();
}

function formatReviewMarkdown(content) {
  let formatted = content;
  if (!formatted.startsWith('#')) {
    formatted = `# Structural Review\n\n${formatted}`;
  }
  return formatted.trim();
}

function parseChapterMarkdown(content) {
  const files = {};
  const chapters = content.split(/^# Chapter /m).slice(1);

  chapters.forEach((chapter, index) => {
    const chapterNum = index + 1;
    files[`story/chapter-${chapterNum}.md`] = `# Chapter ${chapter}`.trim();
  });

  return files;
}

// ─── Helper Functions ────────────────────────────────────────────────

function createPlaceholder(stepKey) {
  const placeholders = {
    author: { 'author.md': '# Author Voice\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in author voice details.' },
    narrator: { 'narrator.md': '# Narrator\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in narrator details.' },
    world: { 'world/world-building.md': '# World Building\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in world building details.' },
    characters: { 'characters/placeholder.md': '# Characters\n\n(Placeholder - decomposition step failed)\n\nPlease manually add character files.' },
    relationships: { 'relationships/questions-answered.md': '# Relationships\n\n(Placeholder - decomposition step failed)\n\nPlease manually fill in relationship details.' },
    structure: { 'outline.md': '# Outline\n\n(Placeholder)', 'story/arc.md': '# Story Arc\n\n(Placeholder)' },
    review: { 'dry-run-audit.md': '# Structural Review\n\n(Placeholder - decomposition step failed)' },
    chapters: { 'story/chapter-1.md': '# Chapter 1\n\n(Placeholder - decomposition step failed)' },
  };

  return placeholders[stepKey] || {};
}

function extractTitleHeuristic(text) {
  // Try to find a title in first few lines
  const lines = text.split('\n').slice(0, 10);
  for (const line of lines) {
    if (line.length > 5 && line.length < 100 && !line.includes('.')) {
      return line.trim();
    }
  }
  return 'Untitled Manuscript';
}

function extractOutlineSection(content) {
  // Extract the outline-like content from the response
  const lines = content.split('\n');
  const outline = [];
  let inOutline = false;

  for (const line of lines) {
    if (line.match(/outline|chapter|act/i)) {
      inOutline = true;
    }
    if (inOutline && (line.startsWith('-') || line.startsWith('*') || line.match(/^\d+\./))) {
      outline.push(line);
    }
  }

  return outline.length > 0 ? outline.join('\n') : '# Outline\n\n' + content.substring(0, 500);
}

function extractArcSection(content) {
  // Extract narrative arc from the response
  const lines = content.split('\n');
  const arc = [];
  const arcKeywords = ['inciting', 'rising', 'climax', 'falling', 'resolution'];

  for (const line of lines) {
    if (arcKeywords.some(kw => line.toLowerCase().includes(kw))) {
      arc.push(line);
    }
  }

  return arc.length > 0 ? arc.join('\n') : '# Story Arc\n\n' + content.substring(0, 500);
}
